spring.application.name=sql-relations
spring.datasource.url=jdbc:postgresql://localhost:5432/hastane_db
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

